/**
 * MatchVenezuelan Cloudflare Worker — Pre-JS SEO Injection
 *
 * Architecture:
 *   Netlify origin → Cloudflare CDN → this Worker → client/bot
 *
 * What it does:
 *   For every HTML response (pages, not assets), it rewrites the <head> using
 *   HTMLRewriter to inject:
 *     - <html lang="..."> attribute (en or es based on path)
 *     - <title>
 *     - meta description
 *     - <link rel="canonical">
 *     - <link rel="alternate" hreflang="..."> pairs
 *     - JSON-LD structured data (highest-value pages only)
 *
 *   This ensures Google and social crawlers see correct per-page metadata
 *   without needing to execute JavaScript.
 *
 * Why not SSR/SSG:
 *   The app is a Vite CSR SPA. Adding a Worker is the fastest, lowest-risk
 *   path to pre-JS SEO — no rebuild pipeline changes, no framework migration.
 *
 * Maintenance:
 *   Run `npm run generate:worker-meta` to regenerate META_MAP from source.
 *   See scripts/generate-worker-meta.mjs for details.
 */

// ---------------------------------------------------------------------------
// META MAP — generated by scripts/generate-worker-meta.mjs + manually curated
// Key: pathname (no trailing slash except root "/")
// ---------------------------------------------------------------------------
const META_MAP = {

  // ---- Core pages ---------------------------------------------------------

  "/": {
    lang: "en",
    title: "MatchVenezuelan — Serious international dating, built on trust",
    description: "MatchVenezuelan connects Venezuelan women with men worldwide for serious relationships. Verified profiles, active moderation, bilingual EN/ES.",
    canonical: "https://matchvenezuelan.com/",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/" },
    ],
    jsonLd: {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "name": "MatchVenezuelan",
      "url": "https://matchvenezuelan.com/",
      "description": "International dating platform connecting Venezuelan women with men worldwide for serious relationships.",
      "potentialAction": {
        "@type": "SearchAction",
        "target": "https://matchvenezuelan.com/preview?q={search_term_string}",
        "query-input": "required name=search_term_string"
      }
    },
  },

  "/es/": {
    lang: "es",
    title: "MatchVenezuelan — Citas internacionales serias, construidas sobre confianza",
    description: "MatchVenezuelan conecta a mujeres venezolanas con hombres de todo el mundo para relaciones serias. Perfiles verificados, moderación activa, bilingüe EN/ES.",
    canonical: "https://matchvenezuelan.com/es/",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/" },
    ],
  },

  "/how-it-works": {
    lang: "en",
    title: "How MatchVenezuelan Works | International Dating, Verification & Safe Meetings",
    description: "A step-by-step guide to how MatchVenezuelan works for both Venezuelan women and Western men — from creating a verified profile to meeting safely in person.",
    canonical: "https://matchvenezuelan.com/how-it-works",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/how-it-works" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/how-it-works" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/how-it-works" },
    ],
  },

  "/es/how-it-works": {
    lang: "es",
    title: "Cómo Funciona MatchVenezuelan | Citas Internacionales, Verificación y Encuentros Seguros",
    description: "Guía paso a paso de cómo funciona MatchVenezuelan para mujeres venezolanas y hombres occidentales: desde crear un perfil verificado hasta conocerse en persona con seguridad.",
    canonical: "https://matchvenezuelan.com/es/how-it-works",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/how-it-works" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/how-it-works" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/how-it-works" },
    ],
  },

  "/safety": {
    lang: "en",
    title: "How to Date Venezuelan Women Safely | Safety Standards at MatchVenezuelan",
    description: "Learn how MatchVenezuelan's moderation system works, how to spot romance scams, how to report suspicious behavior, and what verified profiles actually mean. Safety is the product.",
    canonical: "https://matchvenezuelan.com/safety",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/safety" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/safety" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/safety" },
    ],
  },

  "/es/safety": {
    lang: "es",
    title: "Cómo Salir con una Venezolana con Seguridad | Estándares de MatchVenezuelan",
    description: "Conoce cómo funciona la moderación de MatchVenezuelan, cómo detectar estafas románticas, cómo denunciar comportamientos sospechosos y qué significan realmente los perfiles verificados.",
    canonical: "https://matchvenezuelan.com/es/safety",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/safety" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/safety" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/safety" },
    ],
  },

  "/faq": {
    lang: "en",
    title: "Venezuelan Dating FAQ | Verification, Safety & How MatchVenezuelan Works",
    description: "Answers to the most common questions about MatchVenezuelan — how verification works, what safety measures exist, pricing, privacy, and how to report.",
    canonical: "https://matchvenezuelan.com/faq",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/faq" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/faq" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/faq" },
    ],
  },

  "/es/faq": {
    lang: "es",
    title: "Preguntas Frecuentes sobre MatchVenezuelan | Verificación, Seguridad y Citas",
    description: "Respuestas a las preguntas más comunes sobre MatchVenezuelan: cómo funciona la verificación, qué medidas de seguridad existen, precios, privacidad y cómo denunciar.",
    canonical: "https://matchvenezuelan.com/es/faq",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/faq" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/faq" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/faq" },
    ],
  },

  "/about": {
    lang: "en",
    title: "About MatchVenezuelan | Our Mission, Team, and Trust Standards",
    description: "MatchVenezuelan was built to connect Venezuelan women and Western men through verified, serious-intent dating. Learn about our mission, moderation standards, and the team behind the platform.",
    canonical: "https://matchvenezuelan.com/about",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/about" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/about" },
    ],
    jsonLd: {
      "@context": "https://schema.org",
      "@type": "Organization",
      "name": "MatchVenezuelan",
      "url": "https://matchvenezuelan.com/",
      "logo": "https://matchvenezuelan.com/logo.webp",
      "description": "International dating platform specializing in connecting Venezuelan women with men worldwide through verified, serious-intent profiles.",
      "sameAs": []
    },
  },

  "/resources": {
    lang: "en",
    title: "Dating Guides & Resources | MatchVenezuelan",
    description: "Practical guides on Venezuelan dating culture, safety, communication, and building a real cross-cultural relationship.",
    canonical: "https://matchvenezuelan.com/resources",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/resources" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/recursos" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/resources" },
    ],
  },

  "/es/recursos": {
    lang: "es",
    title: "Guías y Recursos de Citas | MatchVenezuelan",
    description: "Guías prácticas sobre cultura de citas venezolana, seguridad, comunicación y cómo construir una relación intercultural real.",
    canonical: "https://matchvenezuelan.com/es/recursos",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/resources" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/recursos" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/resources" },
    ],
  },

  // ---- High-value landing pages (EN) --------------------------------------

  "/meet-venezuelan-women": {
    lang: "en",
    title: "Meet Venezuelan Women | Verified Profiles for Serious Relationships | MatchVenezuelan",
    description: "Connect with verified Venezuelan women seeking serious international relationships. Free for women. Moderated, bilingual, and built on trust.",
    canonical: "https://matchvenezuelan.com/meet-venezuelan-women",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/meet-venezuelan-women" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/conocer-mujeres-venezolanas" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/meet-venezuelan-women" },
    ],
  },

  "/es/conocer-mujeres-venezolanas": {
    lang: "es",
    title: "Conocer Mujeres Venezolanas | Perfiles Verificados para Relaciones Serias | MatchVenezuelan",
    description: "Conecta con mujeres venezolanas verificadas que buscan relaciones internacionales serias. Gratuito para mujeres. Moderado, bilingüe y construido sobre confianza.",
    canonical: "https://matchvenezuelan.com/es/conocer-mujeres-venezolanas",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/meet-venezuelan-women" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/conocer-mujeres-venezolanas" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/meet-venezuelan-women" },
    ],
  },

  "/venezuelan-dating-site": {
    lang: "en",
    title: "Venezuelan Dating Site | Verified Profiles, Real Relationships | MatchVenezuelan",
    description: "The most trusted Venezuelan dating site for serious relationships. Verified profiles, active moderation, and a bilingual platform built for genuine connection.",
    canonical: "https://matchvenezuelan.com/venezuelan-dating-site",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/venezuelan-dating-site" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/sitio-de-citas-venezolanas" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/venezuelan-dating-site" },
    ],
  },

  "/venezuelan-women-for-marriage": {
    lang: "en",
    title: "Venezuelan Women for Marriage | Serious Intent Dating | MatchVenezuelan",
    description: "Meet Venezuelan women interested in marriage and long-term commitment. Verified profiles, transparent intent-setting, and a platform built for serious relationships.",
    canonical: "https://matchvenezuelan.com/venezuelan-women-for-marriage",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/venezuelan-women-for-marriage" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/mujeres-venezolanas-para-matrimonio" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/venezuelan-women-for-marriage" },
    ],
  },

  "/venezuelan-dating-culture": {
    lang: "en",
    title: "Venezuelan Dating Culture | What to Know Before You Start | MatchVenezuelan",
    description: "Understanding Venezuelan dating culture: family dynamics, communication styles, relationship expectations, and how to approach cross-cultural relationships with respect.",
    canonical: "https://matchvenezuelan.com/venezuelan-dating-culture",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/venezuelan-dating-culture" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/cultura-de-citas-venezolanas" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/venezuelan-dating-culture" },
    ],
  },

  "/es/cultura-de-citas-venezolanas": {
    lang: "es",
    title: "Cultura de Citas Venezolanas | Lo Que Debes Saber Antes de Empezar | MatchVenezuelan",
    description: "Comprende la cultura de citas venezolana: dinámica familiar, estilos de comunicación, expectativas relacionales y cómo acercarte a las relaciones interculturales con respeto.",
    canonical: "https://matchvenezuelan.com/es/cultura-de-citas-venezolanas",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/venezuelan-dating-culture" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/cultura-de-citas-venezolanas" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/venezuelan-dating-culture" },
    ],
  },

  "/travel-to-meet-venezuelan-women": {
    lang: "en",
    title: "Travel to Meet Venezuelan Women | Safety, Planning & Real Expectations | MatchVenezuelan",
    description: "A practical guide to traveling for an in-person meeting with a Venezuelan woman — safety protocols, what to expect, and how to plan a first meeting responsibly.",
    canonical: "https://matchvenezuelan.com/travel-to-meet-venezuelan-women",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/travel-to-meet-venezuelan-women" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/viajar-para-conocer-mujeres-venezolanas" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/travel-to-meet-venezuelan-women" },
    ],
  },

  "/es/viajar-para-conocer-mujeres-venezolanas": {
    lang: "es",
    title: "Viajar para Conocer Mujeres Venezolanas | Seguridad, Planificación y Expectativas | MatchVenezuelan",
    description: "Guía práctica para viajar a un encuentro en persona con una mujer venezolana — protocolos de seguridad, qué esperar y cómo planificar un primer encuentro de forma responsable.",
    canonical: "https://matchvenezuelan.com/es/viajar-para-conocer-mujeres-venezolanas",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/travel-to-meet-venezuelan-women" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/viajar-para-conocer-mujeres-venezolanas" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/travel-to-meet-venezuelan-women" },
    ],
  },

  // ---- City landing pages (highest-traffic subset) ------------------------
  // Pattern fallback covers the rest — see META_MAP_PATTERNS below

  "/venezuelan-women-in-miami": {
    lang: "en",
    title: "Venezuelan Women in Miami | Little Venezuela, Doral & South Florida Diaspora | MatchVenezuelan",
    description: "Miami has the largest Venezuelan diaspora in the US. Connect with verified Venezuelan women in Doral, Kendall, and across South Florida on MatchVenezuelan.",
    canonical: "https://matchvenezuelan.com/venezuelan-women-in-miami",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/venezuelan-women-in-miami" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/mujeres-venezolanas-en-miami" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/venezuelan-women-in-miami" },
    ],
  },

  "/es/mujeres-venezolanas-en-miami": {
    lang: "es",
    title: "Mujeres Venezolanas en Miami | Little Venezuela, Doral y Diáspora del Sur de Florida | MatchVenezuelan",
    description: "Miami tiene la mayor diáspora venezolana en EE.UU. Conecta con mujeres venezolanas verificadas en Doral, Kendall y todo el sur de Florida en MatchVenezuelan.",
    canonical: "https://matchvenezuelan.com/es/mujeres-venezolanas-en-miami",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/venezuelan-women-in-miami" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/mujeres-venezolanas-en-miami" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/venezuelan-women-in-miami" },
    ],
  },

  "/venezuelan-women-in-houston": {
    lang: "en",
    title: "Venezuelan Women in Houston | Energy Corridor, Sugar Land & Southwest Diaspora | MatchVenezuelan",
    description: "Houston's Venezuelan community is built around the energy industry. Connect with verified Venezuelan women across the Greater Houston area on MatchVenezuelan.",
    canonical: "https://matchvenezuelan.com/venezuelan-women-in-houston",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/venezuelan-women-in-houston" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/mujeres-venezolanas-en-houston" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/venezuelan-women-in-houston" },
    ],
  },

  "/venezuelan-women-in-madrid": {
    lang: "en",
    title: "Venezuelan Women in Madrid | Carabanchel, Vallecas & European Gateway Diaspora | MatchVenezuelan",
    description: "Madrid hosts one of Europe's largest Venezuelan communities. Connect with verified Venezuelan women in Carabanchel, Vallecas, and across the Spanish capital on MatchVenezuelan.",
    canonical: "https://matchvenezuelan.com/venezuelan-women-in-madrid",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/venezuelan-women-in-madrid" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/mujeres-venezolanas-en-madrid" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/venezuelan-women-in-madrid" },
    ],
  },

  "/es/mujeres-venezolanas-en-madrid": {
    lang: "es",
    title: "Mujeres Venezolanas en Madrid | Carabanchel, Vallecas y Diáspora Europea | MatchVenezuelan",
    description: "Madrid alberga una de las comunidades venezolanas más grandes de Europa. Conecta con mujeres venezolanas verificadas en Carabanchel, Vallecas y toda la capital española en MatchVenezuelan.",
    canonical: "https://matchvenezuelan.com/es/mujeres-venezolanas-en-madrid",
    alternates: [
      { hreflang: "en",        href: "https://matchvenezuelan.com/venezuelan-women-in-madrid" },
      { hreflang: "es",        href: "https://matchvenezuelan.com/es/mujeres-venezolanas-en-madrid" },
      { hreflang: "x-default", href: "https://matchvenezuelan.com/venezuelan-women-in-madrid" },
    ],
  },

};

// ---------------------------------------------------------------------------
// PATTERN FALLBACKS — for long-tail landing pages not in META_MAP
// Ordered from most specific to least specific.
// ---------------------------------------------------------------------------
const META_MAP_PATTERNS = [

  // ES city pages (generic)
  {
    match: (p) => p.startsWith("/es/mujeres-venezolanas-en-"),
    build: (p) => {
      const city = p.replace("/es/mujeres-venezolanas-en-", "").replace(/-/g, " ");
      const cityTitle = city.charAt(0).toUpperCase() + city.slice(1);
      const enSlug = p.replace("/es/mujeres-venezolanas-en-", "/venezuelan-women-in-");
      return {
        lang: "es",
        title: `Mujeres Venezolanas en ${cityTitle} | MatchVenezuelan`,
        description: `Conoce mujeres venezolanas verificadas en ${cityTitle} buscando relaciones serias en MatchVenezuelan.`,
        canonical: `https://matchvenezuelan.com${p}`,
        alternates: [
          { hreflang: "en",        href: `https://matchvenezuelan.com${enSlug}` },
          { hreflang: "es",        href: `https://matchvenezuelan.com${p}` },
          { hreflang: "x-default", href: `https://matchvenezuelan.com${enSlug}` },
        ],
      };
    },
  },

  // EN city pages (generic)
  {
    match: (p) => p.startsWith("/venezuelan-women-in-"),
    build: (p) => {
      const city = p.replace("/venezuelan-women-in-", "").replace(/-/g, " ");
      const cityTitle = city.charAt(0).toUpperCase() + city.slice(1);
      return {
        lang: "en",
        title: `Venezuelan Women in ${cityTitle} | MatchVenezuelan`,
        description: `Meet verified Venezuelan women in ${cityTitle} looking for serious relationships on MatchVenezuelan.`,
        canonical: `https://matchvenezuelan.com${p}`,
        alternates: [
          { hreflang: "en",        href: `https://matchvenezuelan.com${p}` },
          { hreflang: "x-default", href: `https://matchvenezuelan.com${p}` },
        ],
      };
    },
  },

  // ES intent/other pages
  {
    match: (p) => p.startsWith("/es/"),
    build: (p) => ({
      lang: "es",
      title: "MatchVenezuelan — Citas internacionales serias",
      description: "Conecta con mujeres venezolanas verificadas para relaciones serias. Gratis para mujeres. Bilingüe EN/ES.",
      canonical: `https://matchvenezuelan.com${p}`,
      alternates: [
        { hreflang: "es",        href: `https://matchvenezuelan.com${p}` },
        { hreflang: "x-default", href: "https://matchvenezuelan.com/" },
      ],
    }),
  },

];

// ---------------------------------------------------------------------------
// HELPERS
// ---------------------------------------------------------------------------

function normalizePath(url) {
  const { pathname } = new URL(url);
  // Strip trailing slash except for root
  return pathname.length > 1 ? pathname.replace(/\/$/, "") : pathname;
}

function resolveMeta(pathname) {
  // Direct match first
  if (META_MAP[pathname]) return META_MAP[pathname];
  // Pattern fallback
  for (const pattern of META_MAP_PATTERNS) {
    if (pattern.match(pathname)) return pattern.build(pathname);
  }
  // Generic fallback — homepage metadata (avoids broken canonical on 404s etc.)
  return META_MAP["/"];
}

function isHtmlRequest(request, response) {
  const accept = request.headers.get("accept") ?? "";
  const ct = response.headers.get("content-type") ?? "";
  // Bots often don't send Accept headers, so also check content-type
  return accept.includes("text/html") || ct.includes("text/html");
}

function isAsset(pathname) {
  return /\.(js|css|webp|jpg|jpeg|png|gif|svg|ico|woff2?|ttf|map|json|txt|xml)$/i.test(pathname);
}

// ---------------------------------------------------------------------------
// HTML REWRITER HANDLERS
// ---------------------------------------------------------------------------

class HtmlLangHandler {
  constructor(lang) { this.lang = lang; }
  element(el) { el.setAttribute("lang", this.lang); }
}

class HeadMetaInjector {
  constructor(meta) { this.meta = meta; this.injected = false; }

  element(el) {
    if (this.injected) return;
    this.injected = true;
    const { title, description, canonical, alternates, jsonLd } = this.meta;

    let html = "";

    // Title
    html += `<title>${escapeHtml(title)}</title>`;

    // Description
    html += `<meta name="description" content="${escapeHtml(description)}">`;

    // Canonical
    html += `<link rel="canonical" href="${escapeHtml(canonical)}">`;

    // og:url
    html += `<meta property="og:url" content="${escapeHtml(canonical)}">`;

    // og:title / og:description (overwrite what static shell has)
    html += `<meta property="og:title" content="${escapeHtml(title)}">`;
    html += `<meta property="og:description" content="${escapeHtml(description)}">`;

    // hreflang alternates
    for (const alt of (alternates ?? [])) {
      html += `<link rel="alternate" hreflang="${escapeHtml(alt.hreflang)}" href="${escapeHtml(alt.href)}">`;
    }

    // JSON-LD (only for pages that have it)
    if (jsonLd) {
      html += `<script type="application/ld+json">${JSON.stringify(jsonLd)}</script>`;
    }

    // Inject BEFORE </head> so it appears early in the head
    el.prepend(html, { html: true });
  }
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// ---------------------------------------------------------------------------
// WORKER ENTRY POINT
// ---------------------------------------------------------------------------

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const pathname = normalizePath(request.url);

    // Pass through assets unchanged — no HTML rewriting needed
    if (isAsset(pathname)) {
      return fetch(request);
    }

    // Fetch the response from origin (Netlify)
    const response = await fetch(request);

    // Only rewrite HTML responses
    if (!isHtmlRequest(request, response)) {
      return response;
    }

    const meta = resolveMeta(pathname);

    // Use HTMLRewriter to stream-transform the response
    return new HTMLRewriter()
      .on("html", new HtmlLangHandler(meta.lang))
      .on("head", new HeadMetaInjector(meta))
      .transform(response);
  },
};
